export const MenuActionTypes = {
  CREATE_MENU_SUCCESS: "CREATE_MENU_SUCCESS",
  CREATE_MENU_ERROR: "CREATE_MENU_ERROR",
  DELETE_MENU_SUCCESS: "DELETE_MENU_SUCCESS",
  DELETE_MENU_ERROR: "DELETE_MENU_ERROR",
  CREATE_MENU_ITEM_SUCCESS: "CREATE_MENU_ITEM_SUCCESS",
  CREATE_MENU_ITEM_ERROR: "CREATE_MENU_ITEM_ERROR"
};

export const CartActionTypes = {
  ADD_ITEMS_TO_CART: "ADD_ITEMS_TO_CART",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  REMOVE_FROM_CART_SUCCESS: "REMOVE_FROM_CART_SUCCESS"
};
