export const MenuActionTypes = {
  CREATE_MENU_SUCCESS: "CREATE_MENU_SUCCESS",
  CREATE_MENU_ERROR: "CREATE_MENU_ERROR",
  DELETE_MENU_SUCCESS: "DELETE_MENU_SUCCESS",
  DELETE_MENU_ERROR: "DELETE_MENU_ERROR",
  CREATE_MENU_ITEM_SUCCESS: "CREATE_MENU_ITEM_SUCCESS",
  CREATE_MENU_ITEM_ERROR: "CREATE_MENU_ITEM_ERROR"
};
